In [1]:
# check if node is valid: within bounds
# and not already visited

def valid(node):
    if(node[0]<=5 and node[1]<=5 and node[0]>=1 and node[1]>=1 and node not in obstacles):
        return True
    return False

In [2]:
import numpy as np
def astar(start,goal):

    maze=[(x,y) for x in range(1,6) for y in range(1,6)] # calculate Mahnattan distances for every valid location
    maze=list(set(maze)-set(obstacles))
    dist=np.sum(np.abs(np.array(goal)-maze),axis=1)

    q=[(dist[maze.index(start)],0,start)]     # initialize variables
    r_state=maze
    r_data=[0]*len(maze)
    r_data[r_state.index(start)]=(dist[maze.index(start)],0)
    cost=0
    while True:
        
        curr_node=q.pop(0) # remove node from fringe and add it to visited list
        print(curr_node[2],end=' ')
        
        i,j=curr_node[2] # extract co-ordinates for future use
        
        if(curr_node[2]==goal): # goal found!
            print("| Total Cost=",cost,"| Effective Cost=",curr_node[1])
            return cost, curr_node[1]
            break
        else: # entertain all possibilities (up,down,left,right)
            nbrs=[(i-1,j),(i,j-1),(i,j+1),(i+1,j)]
            for i in range(4):
                if(valid(nbrs[i])):
                    # check if node is new or it exists in queue if new node, then simply insert
                    # else check if new path is better than old path
                    if (r_data[r_state.index(nbrs[i])]==0
                    or (curr_node[1]+1)<r_data[r_state.index(nbrs[i])][1]):
                        r_data[r_state.index(nbrs[i])]=((dist[maze.index(nbrs[i])]+curr_node[1]+1),(curr_node[1]+1))
                        q.append(((dist[maze.index(nbrs[i])]+curr_node[1]+1),(curr_node[1]+1),nbrs[i]))
            q.sort()
            cost+=1

In [3]:
import numpy as np

# below code snippet is for showing the initial state of 
# the maze diagrammatically
maze=np.zeros(25)
maze[4]=maze[6]=maze[13]=maze[14]=maze[16]=maze[19]=1
maze[0]=2
maze[9]=maze[11]=maze[20]=maze[24]=3

maze=maze.reshape((5,5))
print(maze)
print("")
# tuples defining the respective entities start state, goal state, and obstacles
start=(1,1)
goals=[(3,2),(5,1),(2,5),(5,5)]
obstacles=[(1,5),(2,2),(3,4),(3,5),(4,2),(4,5)]
global obstacles

cost_tot=0
cost_eff=0
while(len(goals)>0):
    
    # find the closest goal using Manhattan Distance
    min_ind=np.argmin(np.sum(np.abs(np.array(goals)-start),axis=1))
    
    # use a-star on the current state and nearest goal found
    scores=astar(start,goals[min_ind])
    cost_tot+=scores[0]
    cost_eff+=scores[1]
    
    # repeat the problem with goal state as new start state
    start=goals[min_ind]
    goals.pop(min_ind)

print("")
print("Total cost:",cost_tot)
print("Effective cost:",cost_eff)

[[2. 0. 0. 0. 1.]
 [0. 1. 0. 0. 3.]
 [0. 3. 0. 1. 1.]
 [0. 1. 0. 0. 1.]
 [3. 0. 0. 0. 3.]]

(1, 1) (1, 2) (2, 1) (3, 1) (3, 2) | Total Cost= 4 | Effective Cost= 3
(3, 2) (3, 1) (4, 1) (5, 1) | Total Cost= 3 | Effective Cost= 3
(5, 1) (5, 2) (5, 3) (5, 4) (5, 5) | Total Cost= 4 | Effective Cost= 4
(5, 5) (5, 4) (4, 4) (5, 3) (4, 3) (3, 3) (2, 3) (2, 4) (2, 5) | Total Cost= 8 | Effective Cost= 7

Total cost: 19
Effective cost: 17
