In [13]:
# Check if node is within the bounds of the maze,
# has not been visited before, and is not an obstacle

def valid(node,visited=[None]):
    if(node[0]<=6 and node[1]<=6 and node[0]>=1 and node[1]>=1
       and node not in visited and node not in obstacles):
        return True
    return False

In [14]:
# Depth-First Search

def dfs(start,goal):
    
    # initialize variables
    stack=[start]
    visited=[]
    cost=0
    
    while True:
        curr_node=stack.pop()
        visited.append(curr_node)
        
        print(curr_node)
        i,j=curr_node
        
        # goal found!
        if(curr_node==goal):
            print("| Cost=",cost)
            break
            
        # entertain all possibilities (up,down,left,right)
        else: 
            if(valid((i-1,j),visited)):stack.append((i-1,j))
            if(valid((i,j-1),visited)):stack.append((i,j-1))
            if(valid((i,j+1),visited)):stack.append((i,j+1))
            if(valid((i+1,j),visited)):stack.append((i+1,j)) 
        cost+=1

In [15]:
# Breadth-First Search

def bfs(start,goal):

    # initialize variables
    queue=[start]
    visited=[]
    cost=0

    while True:
        curr_node=queue.pop(0)
        visited.append(curr_node)
        
        print(curr_node,end=' ')
        i,j=curr_node
        
        # goal found!
        if(curr_node==goal):
            print("| Cost=",cost)
            break
            
        # entertain all possibilities (up,down,left,right)
        else:
            nbrs=[(i-1,j),(i,j-1),(i,j+1),(i+1,j)]
            for k in range(4):
                if(valid(nbrs[k],visited)):
                    queue.append(nbrs[k])
                    visited.append(nbrs[k])
        cost+=1

In [21]:
def dls(start,goal):      # Depth-Limited Search
    for l in range(3,13): # increase depth iteratively
        stack=[(0,start)] #initialize stack
        visited=[]
        cost=0
        
        # terminates the iterative deepening, when goal is found
        goal_found=False
        
        while True:
            if(len(stack)==0):
                print("Goal not found")
                break
            curr_node=stack.pop()
            visited.append(curr_node[1])
            
            if(curr_node[0]>l): # ignore if depth exceeds limit
                continue
            else:
                print(curr_node[1],end=' ') # do the usual dfs algo
                i,j=curr_node[1]
                if(curr_node[1]==goal):
                    print("| Cost=",cost," | Depth = ",l)
                    goal_found=True
                    break
                else: # entertain all possibilites(up,down,left,right)
                    if(valid((i-1,j),visited)):stack.append(((curr_node[0]+1),(i-1,j)))
                    if(valid((i,j-1),visited)):stack.append(((curr_node[0]+1),(i,j-1)))
                    if(valid((i,j+1),visited)):stack.append(((curr_node[0]+1),(i,j+1)))
                    if(valid((i+1,j),visited)):stack.append(((curr_node[0]+1),(i+1,j))) 
                cost+=1
        if(goal_found): break

In [17]:
def ucs(start,goal): # Uniform-cost Search
    q=[(0,start)] # tuple of the form (dist from goal,coordinates)
    q_states=[start]
    visited=[]
    cost=0

    while True:  
        curr_node=q.pop(0) # eject from fringe
        q_states.pop(0)
        
        visited.append(curr_node[1])
        print(curr_node[1],end=' ')
        i,j=curr_node[1]
        
        if(curr_node[1]==goal): # goal found
            print("| Cost=",cost)
            break
        else:
            nbrs=[(i-1,j),(i,j-1),(i,j+1),(i+1,j)] # generate possible neighbors
            
            for i in range(4):
                # if the nbr does not exist in visited+fringe, insert in fringe
                if(valid(nbrs[i],visited) and nbrs[i] not in q_states):
                    q.append(((curr_node[0]+1),nbrs[i]))
                    q_states.append(nbrs[i])
                    
                # better path found! -> update the node
                elif(nbrs[i] in q_states and q[q_states.index(nbrs[i])][0]>(curr_node[0]+1)):
                    q[q_states.index(nbrs[i])][0]=curr_node[0]+1
                    
            # prioritize least cost path
            q.sort()
            cost+=1

In [18]:
import numpy as np

def gbfs(start,goal): # Greedy Best-First Search
    maze=[(x,y) for x in range(1,7) for y in range(1,7)]     # generate Manhattan distances
    maze=list(set(maze)-set(obstacles))
    dist=np.sum(np.array([6,6])-maze,axis=1)
    
    q=[(10,0,start)]     #(h(n),g(n),node)
    r_state=maze         # lookup table for nodes
    r_data=[0]*len(maze) # lookup table for the nodes' corresponding (h(n),g(n))
    cost=0

    while True:
        curr_node=q.pop(0)
        print(curr_node[2])
        i,j=curr_node[2]
        
        if(curr_node[2]==goal):  # goal found!-> terminate
            print("| Cost=",cost)
            break
        else:
            nbrs=[(i-1,j),(i,j-1),(i,j+1),(i+1,j)]  # generate all neighbors
            for i in range(4):
                # update lookup table if node visited for the first time,
                # or if a better path exists to the node
                if(valid(nbrs[i])):
                    if (r_data[r_state.index(nbrs[i])]==0
                    or (curr_node[1]+1)<r_data[r_state.index(nbrs[i])][1]):
                        r_data[r_state.index(nbrs[i])]=(dist[maze.index(nbrs[i])],(curr_node[1]+1))
                        q.append((dist[maze.index(nbrs[i])],(curr_node[1]+1),nbrs[i]))
            q.sort()
            cost+=1

In [19]:
import numpy as np

def astar(start,goal): # A* Search
    maze=[(x,y) for x in range(1,7) for y in range(1,7)]     # generate Manhattan distances
    maze=list(set(maze)-set(obstacles))
    dist=np.sum(np.array([6,6])-maze,axis=1)
    
    q=[(10,10,0,start)]  #(h(n)+g(n),h(n),g(n),node)
    r_state=maze         # lookup table for nodes
    r_data=[0]*len(maze) # lookup table for the nodes' corresponding (h(n),g(n))
    cost=0

    while True:
        curr_node=q.pop(0)
        print(curr_node[3])
        i,j=curr_node[3]
        
        if(curr_node[3]==goal):  # goal found!-> terminate
            print("| Cost=",cost)
            break
        else:
            nbrs=[(i-1,j),(i,j-1),(i,j+1),(i+1,j)]  # generate all neighbors
            for i in range(4):
                if(valid(nbrs[i])):
                    # update lookup table if node visited for the first time,
                    # or if a better path exists to the node
                    if (r_data[r_state.index(nbrs[i])]==0
                    or (curr_node[2]+1)<r_data[r_state.index(nbrs[i])][1]):
                        r_data[r_state.index(nbrs[i])]=(dist[maze.index(nbrs[i])]+curr_node[2]+1,(curr_node[2]+1))
                        q.append((dist[maze.index(nbrs[i])]+curr_node[2]+1,dist[maze.index(nbrs[i])],(curr_node[2]+1),nbrs[i]))
            q.sort()
            cost+=1

In [1]:
import numpy as np

# below code snippet is for showing the initial state of 
# the maze diagrammatically
maze=np.zeros(36)
maze[3]=maze[7]=maze[8]=maze[9]=maze[20]=1
maze[28]=maze[22]=maze[23]=maze[25]=maze[26]=1
maze[30]=2
maze[5]=3

maze=maze.reshape((6,6))
print(maze)
print("")

[[0. 0. 0. 1. 0. 3.]
 [0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 1.]
 [0. 1. 1. 0. 1. 0.]
 [2. 0. 0. 0. 0. 0.]]



In [22]:
# Execution Block

f=open('input.txt',encoding='utf8')

dims=[int(y.strip()) for y in f.readline().split(',')]

initial=[y.strip() for y in f.readline().split(';')]
start=int(initial[0][0]),int(initial[0][2])
goal=int(initial[1][0]),int(initial[1][2])

obstacles=[y.strip() for y in f.readline().split(';')]
for i in range(len(obstacles)):
    obstacles[i]=int(obstacles[i][0]),int(obstacles[i][2])
    
global obstacles

algo=['dfs','bfs','dls','ucs','gbfs','astar']
for i in range(6):
    print("Algo used:",algo[i])
    eval(algo[i]+"(start,goal)")
    print("")

Algo used: dfs
(1, 1)
(2, 1)
(3, 1)
(4, 1)
(5, 1)
(6, 1)
(6, 2)
(4, 2)
(4, 3)
(4, 4)
(5, 4)
(6, 4)
(6, 5)
(6, 6)
| Cost= 13

Algo used: bfs
(1, 1) (1, 2) (2, 1) (1, 3) (3, 1) (1, 4) (2, 3) (4, 1) (1, 5) (2, 4) (4, 2) (5, 1) (1, 6) (3, 4) (4, 3) (6, 1) (2, 6) (4, 4) (6, 2) (3, 6) (5, 4) (5, 5) (6, 4) (5, 6) (6, 5) (6, 6) | Cost= 25

Algo used: dls
(1, 1) (2, 1) (3, 1) (4, 1) (1, 2) (1, 3) (2, 3) (1, 4) Goal not found
(1, 1) (2, 1) (3, 1) (4, 1) (5, 1) (4, 2) (1, 2) (1, 3) (2, 3) (2, 4) (1, 4) (1, 5) Goal not found
(1, 1) (2, 1) (3, 1) (4, 1) (5, 1) (6, 1) (4, 2) (4, 3) (1, 2) (1, 3) (2, 3) (2, 4) (3, 4) (1, 4) (1, 4) Goal not found
(1, 1) (2, 1) (3, 1) (4, 1) (5, 1) (6, 1) (6, 2) (4, 2) (4, 3) (4, 4) (1, 2) (1, 3) (2, 3) (2, 4) (1, 4) (1, 5) (1, 4) Goal not found
(1, 1) (2, 1) (3, 1) (4, 1) (5, 1) (6, 1) (6, 2) (4, 2) (4, 3) (4, 4) (5, 4) (3, 4) (1, 2) (1, 3) (2, 3) (1, 4) (1, 5) (1, 6) (2, 6) (3, 6) Goal not found
(1, 1) (2, 1) (3, 1) (4, 1) (5, 1) (6, 1) (6, 2) (4, 2) (4, 3) (4, 4) (5