In [6]:
# check if node is valid: within bounds
# and not already visited

def valid(node,visited):
    if(node[0]<=5 and node[1]<=5 and node[0]>=1 and node[1]>=1 
       and node not in visited and node not in obstacles):
        return True
    return False

In [7]:
# Breadth-First Search

def bfs(start,goal,x):

    # initialize variables
    queue=[start]
    visited=[]
    cost=0

    while True:
        # remove node from fringe and add it to visited list
        curr_node=queue.pop(0)
        visited.append(curr_node)
        
        # extract co-ordinates for future use
        i,j=curr_node
        
        # goal found!
        if(curr_node==goal): return cost
        
        # entertain all possibilities (up,down,left,right)
        else:
            nbrs=[(i-1,j),(i,j-1),(i,j+1),(i+1,j)]
            random.seed(x)
            random.shuffle(nbrs)
            
            for i in range(4):
                if(valid(nbrs[i],visited)):
                    queue.append(nbrs[i])
                    visited.append(nbrs[i])
        cost+=1

In [8]:
import random
import numpy as np

# below code snippet is for showing the 
# initial state of the maze diagrammatically
maze=np.zeros(25)
maze[4]=maze[6]=maze[13]=maze[14]=maze[16]=maze[19]=1
maze[0]=2
maze[23]=2
maze[9]=maze[11]=maze[20]=maze[24]=3

maze=maze.reshape((5,5))
print(maze)

[[2. 0. 0. 0. 1.]
 [0. 1. 0. 0. 3.]
 [0. 3. 0. 1. 1.]
 [0. 1. 0. 0. 1.]
 [3. 0. 0. 2. 3.]]


In [9]:
#=======================================#
#               For Agent A
#=======================================#



costA=[]

for i in range(10):

    # tuples defining the respective entities
    # start state, goal state, and obstacles
    
    start=(1,1)
    goals=[(3,2),(5,1),(2,5),(5,5)]
    obstacles=[(1,5),(2,2),(3,4),(3,5),(4,2),(4,5)]

    cost=0 # total cost to find all goals in the maze

    while(len(goals)>0):
        # find the closest goal using Manhattan Distance
        min_ind=np.argmin(np.sum(np.abs(np.array(goals)-start),axis=1))

        # use bfs on the current state and nearest goal found
        cost+=bfs(start,goals[min_ind],i)

        # repeat the problem with goal state as new start state
        start=goals[min_ind]
        goals.pop(min_ind)

    costA.append(cost)

In [10]:
#=======================================#
#              For Agent B
#=======================================#


costB=[]

for i in range(10):

    # tuples defining the respective entities
    # start state, goal state, and obstacles
    start=(5,4)
    goals=[(3,2),(5,1),(2,5),(5,5)]
    obstacles=[(1,5),(2,2),(3,4),(3,5),(4,2),(4,5)]

    cost=0 # total cost to find all goals in the maze

    while(len(goals)>0):
        # find the closest goal using Manhattan Distance
        min_ind=np.argmin(np.sum(np.abs(np.array(goals)-start),axis=1))

        # use bfs on the current state and nearest goal found
        cost+=bfs(start,goals[min_ind],i)

        # repeat the problem with goal state as new start state
        start=goals[min_ind]
        goals.pop(min_ind)

    costB.append(cost)

In [11]:
# display round-wise scores of each player
print(costA)
print(costB)
    
# convert to NumPy array for easy comparison
costA=np.array(costA)
costB=np.array(costB)


a_win=np.count_nonzero(costA<costB) # number of games A has won
b_win=np.count_nonzero(costA>costB) # number of games B has won

# check who is the winner
if(a_win>b_win):
    print("A is the winner with " ,a_win," wins")
elif(a_win<b_win):
    print("B is the winner with " ,b_win," wins")
else:
    print("Draw, both have" ,a_win,"wins")

[42, 45, 38, 45, 42, 42, 41, 42, 47, 43]
[34, 37, 30, 37, 35, 34, 34, 34, 38, 34]
B is the winner with  10  wins
