In [1]:
# check if node is valid: within bounds
# and not already visited

def valid(node):
    if(node[0]<=5 and node[1]<=5 and node[0]>=1 and node[1]>=1 
    and node not in obstacles):
        return True
    return False

In [2]:
import random
import numpy as np
import math

# below code snippet is for
# showing the initial state of 
# the maze diagrammatically
maze=np.zeros(25)
maze[4]=maze[6]=maze[13]=maze[14]=maze[16]=maze[19]=1
maze[0]=2
maze[23]=2
maze[9]=maze[11]=maze[20]=maze[24]=3

maze=maze.reshape((5,5))
print(maze)

[[2. 0. 0. 0. 1.]
 [0. 1. 0. 0. 3.]
 [0. 3. 0. 1. 1.]
 [0. 1. 0. 0. 1.]
 [3. 0. 0. 2. 3.]]


In [3]:
# evaluation function for leaves of game tree
# sum of inverse Manhattan and inverse Euclidean distances
# from each of the remaining goals, bonus of +3 if agent is on goal

def eval_func(currState,agent,goals):
    i,j=currState[0][agent]
    k,l=currState[0][1-agent]
    score=0
    for goal in currState[1]:
        a,b=goal
        score+=1/(abs(a-i)+abs(b-j))+1/(math.sqrt((a-i)**2+(b-j)**2))
    if(currState[0][agent] in goals):
        score+=3
    return score

In [4]:
# max_part of minimax algorithm

def max_part(currState,agent):
    
    temp=[x[:] for x in currState]
    i,j=temp[0][agent]
    
    #collect neighbours
    nbrs=[(i-1,j),(i,j-1),(i+1,j),(i,j+1)]
    tru_nbrs=[]
    
    #collect valid neighbours
    for i in nbrs:
        if(valid(i)): tru_nbrs.append(i)         
    val=-99999
    scores=[]
    for j in tru_nbrs:       
        new_state=[x[:] for x in currState]
        new_state[0][agent]=j
                
        for i in range(len(new_state[1])):
            if(new_state[0][agent]==new_state[1][i]):
                new_state[1].pop(i)
                break
        
        #min moves    
        scores.append(min_part(new_state,1-agent))
        
    #return max from min moves
    return tru_nbrs[scores.index(max(scores))]

In [5]:
# min part of minimax algo
# since depth is 1, the children of 
# min component will be leaves,
# a.k.a the heuristic values of positions

def min_part(currState,agent):
    
    temp=[x[:] for x in currState]
    i,j=temp[0][agent]
    
    #collect neighbours
    nbrs=[(i-1,j),(i,j-1),(i+1,j),(i,j+1)]
    tru_nbrs=[]
    
     #collect valid neighbours
    for i in nbrs:
        if(valid(i)): tru_nbrs.append(i)
            
    val=99999
    scores=[]
    for j in tru_nbrs:
        
        new_state=[x[:] for x in currState]
        new_state[0][agent]=j
        
        for i in range(len(new_state[1])):
            if(new_state[0][agent]==new_state[1][i]):
                new_state[1].pop(i)
                break
        #max moves        
        scores.append(eval_func(new_state,1-agent,goals))
    
    #return min from max moves    
    return min(scores)

In [6]:
# definition of problem statement
# and various components

goals=[(3,2),(5,1),(2,5),(5,5)]
gameState=[[(1,1),(5,4)],[(3,2),(5,1),(2,5),(5,5)]]
global obstacles
obstacles=[(1,5),(2,2),(3,4),(3,5),(4,2),(4,5)]

global obstacles

player_id={ 0:'A', 1:'B'}

score=[0,0]

while(True):
    
    for a in range(2):
        gameState[0][a]=max_part(gameState,a)
        print("Player ", player_id[a],"moves to: ", gameState[0][a],'\t', end='')
        for i in range(len(gameState[1])):
            if(gameState[0][a]==gameState[1][i]):
                gameState[1].pop(i)
                goals.pop(i)
                score[a]+=10
                break
        else: score[a]-=1
        if(len(gameState[1])==0): break
            
    if(len(gameState[1])==0): break
    print("Current scores: A =",score[0],", B =",score[1])
        
print("\nFinal scores: A =",score[0],", B =",score[1])

if(score[0]<score[1]): print("B is the winner")
elif(score[0]>score[1]): print("A is the winner")
else:  print("Drawn game")

Player  A moves to:  (2, 1) 	Player  B moves to:  (5, 5) 	Current scores: A = -1 , B = 10
Player  A moves to:  (3, 1) 	Player  B moves to:  (5, 4) 	Current scores: A = -2 , B = 9
Player  A moves to:  (3, 2) 	Player  B moves to:  (5, 3) 	Current scores: A = 8 , B = 8
Player  A moves to:  (3, 1) 	Player  B moves to:  (5, 2) 	Current scores: A = 7 , B = 7
Player  A moves to:  (3, 2) 	Player  B moves to:  (5, 1) 	Current scores: A = 6 , B = 17
Player  A moves to:  (3, 3) 	Player  B moves to:  (5, 2) 	Current scores: A = 5 , B = 16
Player  A moves to:  (2, 3) 	Player  B moves to:  (5, 3) 	Current scores: A = 4 , B = 15
Player  A moves to:  (2, 4) 	Player  B moves to:  (4, 3) 	Current scores: A = 3 , B = 14
Player  A moves to:  (2, 5) 	
Final scores: A = 13 , B = 14
B is the winner
