In [1]:
import numpy as np

def sigmoid (x): # activation function
    return 1/(1 + np.exp(-x))

X = np.array([[0.6, 0.1], [0.2, 0.3]]) # test data
Y = np.array([[1.0, 0.0], [0.0, 1.0]]) # output labels

epoch = 50 # number of epochs for which backprop is to be run
lr = 0.1   # learning rate

W_h = np.array([[0.1, 0.0, 0.3], [-0.2, 0.2, -0.4]])    # weights in hidden layer
B_h = np.array([0.1, 0.2, 0.5])                         # bias in hidden layer
W_o = np.array([[-0.4, 0.2], [0.1, -0.1], [0.6, -0.2]]) # weights in output layer
B_o = np.array([-0.1, 0.6])                             # bias in output layer

In [2]:
for e in range(epoch):
    
    for i in range(X.shape[0]):
        
        h_temp = np.dot(X[i],W_h) + B_h  # forward pass from input -> hidden
        h_act = sigmoid(h_temp)          # activate hidden-layer neurons
    
        o_temp = np.dot(h_act,W_o) + B_o # forward pass from hidden -> output
        output = sigmoid(o_temp)         # activate output-layer neurons
        
        del_out = (Y[i] - output) * output * (1 - output)          # error in output
        dW_o = lr * np.array([h_act]).T.dot(np.array([del_out]))   # find delta(Weight_output)
        dB_o = lr * del_out * 1                                    # find delta(Bias_output)
        
        del_hidden = h_act * (1 - h_act) * W_o.dot(del_out.T)      # error in internal activation
        dW_h = lr * np.array([X[i]]).T.dot(np.array([del_hidden])) # find delta(Weight_hidden)
        dB_h = lr * del_hidden * 1                                 # find delta(Bias_hidden)
        
        # update the weights and biases accordingly
        W_o += dW_o
        B_o += dB_o
        W_h += dW_h
        B_h += dB_h
    
    if e in [0,1,49]: # print parameters for 1st, 2nd and 50th iterations
        print("Iteration: ", e+1,"\n")
        print("Weights in hidden layer: \n" , str(W_h),"\n")
        print("Biases in hidden layer: \n" , str(B_h),"\n")
        print("Weights in output layer: \n" ,str(W_o),"\n")
        print("Biases in output layer: \n" , str(B_o),"\n\n\n")

Iteration:  1 

Weights in hidden layer: 
 [[ 9.92162570e-02  2.72431456e-04  3.00868637e-01]
 [-1.99667657e-01  1.99889457e-01 -4.00487120e-01]] 

Biases in hidden layer: 
 [0.09985118 0.20006418 0.499868  ] 

Weights in output layer: 
 [[-0.40063383  0.19673691]
 [ 0.09892641 -0.10310539]
 [ 0.59950097 -0.20417922]] 

Biases in output layer: 
 [-0.1016944   0.59424127] 



Iteration:  2 

Weights in hidden layer: 
 [[ 0.09843748  0.00054864  0.30174373]
 [-0.19933512  0.19977811 -0.40097576]] 

Biases in hidden layer: 
 [0.09970904 0.20013109 0.49974026] 

Weights in output layer: 
 [[-0.40125028  0.19353339]
 [ 0.09787272 -0.10614852]
 [ 0.59902536 -0.20829079]] 

Biases in output layer: 
 [-0.10335376  0.58859417] 



Iteration:  50 

Weights in hidden layer: 
 [[ 0.06519173  0.01597844  0.34831635]
 [-0.18368757  0.19330999 -0.42661493]] 

Biases in hidden layer: 
 [0.09727073 0.20324803 0.49385811] 

Weights in output layer: 
 [[-0.41708125  0.09743366]
 [ 0.06374033 -0.19230297]